default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: praiasereia
  password: Sereia#2024
  host: praiasereia.mysql.dbaas.com.br
  port: 3306

development:
  <<: *default
  database: praiasereia

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
